# permissions for end users to edit instaslices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: instaslice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: instaslicev2
    app.kubernetes.io/part-of: instaslicev2
    app.kubernetes.io/managed-by: kustomize
  name: instaslice-editor-role
rules:
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices/status
  verbs:
  - get
